apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myappbomba.fullname" . }}-deployment
  labels:
    app: myapp
  {{- include "myappbomba.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: myapp
    {{- include "myappbomba.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: myapp
      {{- include "myappbomba.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deployment.myapp.image.repository }}:{{ .Values.deployment.myapp.image.tag
          | default .Chart.AppVersion }}
        name: myapp
        ports:
        - containerPort: 80
        resources: {}