apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myappbomba.fullname" . }}-ingress
  labels:
  {{- include "myappbomba.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.fuf.me
    http:
      paths:
      - backend:
          service:
            name: '{{ include "myappbomba.fullname" . }}-service'
            port:
              number: 8081
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - myapp.fuf.me