deployment:
  myapp:
    image:
      repository: k3d-reg.localhost:5111/myapp
      tag: latest
  replicas: 3

kubernetesClusterDomain: fuf.me
service:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8082
  type: LoadBalancer
