deployment:
  myapp:
    image:
      repository: k3d-reg.localhost:5111/myapp
      tag: 0.3.0
  replicas: 2

kubernetesClusterDomain: fuf.me
service:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8082
  type: ClusterIP
